import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn( "min-h-screen w-full ",inter.className ,  { "debug-screens": process.env.NODE_ENV === "development" })}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
        >
          <Toaster
          position="top-right"
          toastOptions={{

            style: {
              border: '2px solid #312F2D',
              color : "black"
            }}}
          />

        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
